Create main.go
go-steem/rpc pull request #8
Opened 2016-09-12 17:33 UTC by faddat

It's 75% yours anyway.  This is a simple STEEM -> rethinkdb JSON-eater.

2016-10-17 14:31 UTC, tchap requested changes
Please address the issues before I can merge this...

2016-10-17 14:31 UTC, tchap commented on examples/ingestron/main.go
> +    Addresses: []string{"192.168.194.98:28015","192.168.194.91:28015","192.168.194.145:28015","192.168.194.209:28015"},
@faddat Weird indentation, at least as I see it in the GitHub UI...

2016-10-17 14:31 UTC, tchap commented on examples/ingestron/main.go
> +        log.Fatalln(err.Error())
@faddat It is enough to return the error, right?

2016-10-17 14:31 UTC, tchap commented on examples/ingestron/main.go
> +var rethinkdbname string = "steemit"
@faddat I don't like the variable name. Should be `dbName` or something. Just use camelCase please...

2016-10-17 14:31 UTC, tchap commented on examples/ingestron/main.go
> +		fmt.Println("rethindb DB already made")
@faddat Doesn't look like the most robust error check. Not sure how the DB driver works, but you are just assuming that getting an error here means that the DB already exists... IMO you should just fail on any error or check that the error is really that the DB already exists, if that is possible to check.

2016-10-17 14:31 UTC, tchap commented on examples/ingestron/main.go
> +		fmt.Println("Probably already made a table for blocks")
@faddat Same here...

2016-10-17 14:31 UTC, tchap commented on examples/ingestron/main.go
> +	Startblock := 3100000
@faddat Weird variable name, should be `startBlock`...

2016-10-17 14:31 UTC, tchap commented on examples/ingestron/main.go
> +	U := uint32(Startblock)
@faddat Please use better variable names...

2016-10-17 14:31 UTC, tchap commented on examples/ingestron/main.go
> +		websocket.SetMonitor(monitorChan))
@faddat I don't think that you need to use auto-reconnect and monitoring, it was just a demo in the example you based this code on. IMO it makes more sense to just drop this and also delete the extra code that is associated with this functionality. Examples should do as little as possible to be examples really...

2016-10-17 14:31 UTC, tchap commented on examples/ingestron/main.go
> +		for props.LastIrreversibleBlockNum-U > 0 {
@faddat This code block is just horrible horrible. Please rewrite it to check for error codes and simply for the code not to look like a pile of rubbish.

2016-10-17 14:31 UTC, tchap commented on examples/ingestron/main.go
> +time.Sleep(time.Duration(config.SteemitBlockInterval) * time.Second)
@faddat Weird indentation... Are you using `go fmt`?

2016-10-17 14:31 UTC, tchap commented on examples/ingestron/main.go
> +		websocket.SetMonitor(monitorChan))
Well, if you want to keep inserting the block continuously, why not...

2016-10-18 01:38 UTC, faddat commented
Pretty sure that I did not intend to send this as a PR-- nevermind-- I did, now I remember.  This is a super-early ingestron that I did submit.  Thank you for the code reveiw.  I'll update and resubmit.  As for go fmt, yes..... but it looks funny to me as well.

2016-12-02 21:20 UTC, faddat commented on examples/ingestron/main.go
> +		fmt.Println("rethindb DB already made")
Hey, I just noticed this-- Thank you very much for the code review!

2016-12-02 21:21 UTC, faddat commented on examples/ingestron/main.go
> +		for props.LastIrreversibleBlockNum-U > 0 {
lol-- my first go app :).  Thanks again :).

2016-12-02 21:22 UTC, faddat commented on examples/ingestron/main.go
> +time.Sleep(time.Duration(config.SteemitBlockInterval) * time.Second)
just 3 or 4 weeks ago I got a good dev env running.  Shamefully, I was probably not using go fmt, or if I was, I wasn't using it right.  Again, many thanks.  I'm revising this app today, and will resubmit the PR in a much different form.

2016-12-02 21:22 UTC, closed without merging